### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackman#19]
From @CS13337 from https://github.com/BlackArch/blackarch-guide/issues/46

> current blackarch installs compile / fail if your python is 3.8 and not python3.7
> 
> running "sudo blackman -a" or "sudo blackman -g blackarch-forensics"
> produced oodles of the same error message in regards to line 178 from /usr/lib/python3.8/site-packages file=sys.stderr
> 
> infact for each and every package it burped out that same error
> 
> yup my python was to new for the install...
> 
> in my case this was in my .bashrc file:
> 
> export PYTHONPATH=${PYTHONPATH}:"/usr/lib/python3.8/:/usr/lib/python3.8/site-packages/"
> 
> me being simple, comment out the line, duplicated the line as follows:
> 
> export PYTHONPATH=${PYTHONPATH}:"/usr/lib/python3.7/:/usr/lib/python3.7/site-packages/"
> 
> after opening new terminal and running the command to install again, all was well in the boxen verse.
> 
> as i'm new here and only complaining cuz i can, i though i would help out instead.
> 
> solution
> insert one line somewhere near the top of the install guide / website mentioning the python version requirement
> 
> CS13337

**Comment by aancw** [comment]
But, I don't see `python` in Blackman source code. Which one is causing the problem?

**Comment by noraj** [comment]
@aancw is right, blackman is written in bash, so you may were installing python tools that doesn't support python 3.8 yet.

Instead of running `blackman -g blackarch-forensics` install only the ones you really need.

**Comment by aancw** [comment]
This issue can be closed.
