### ISSUE TITLE
Code repo of Loot is not available

### ISSUE THREAD

**Issue by SilverBut** [BlackArch/blackman#5]
While executing `blackman -g blackarch`:

> ....
> Cloning Loot git repo...
> Cloning into bare repository '/tmp/loot/Loot'...
> Username for 'https://github.com':
> ....

Seems a contributor of Loot, GuerrillaWarfare, have deleted his Github account, and thus cloning from https://github.com/GuerrillaWarfare/Loot.git is not possible.

Maybe you need to change it to another source.

**Comment by SilverBut** [comment]
A possible solution is to modify this file

> .blackarch/packages/loot/PKGBUILD

and replace all URIs containing Loot.git into:

> https://github.com/loot/loot.git

Maybe a discussion on the modify is required.

**Comment by PedroSFreitas** [comment]
@SilverBut was removed.
